---
title: "correlation"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: 
      collapsed: false
      smooth_scroll: false
      number_sections: true
      fig_caption: TRUE
    css: "style.css"
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(fpp3)
library(tsibble) #yearweek
#univariate and multivariate time series forecasting models, tsibble
library(fable) 

library(tidyverse)
library(here)
library(data.table)
library(lubridate)
library(dplyr)

#new library
library(GGally)

library(here)
source(here("source","get_fpp3.R"))
```

```{r}
# 1. Load Data
glimpse(aus_livestock)

# 2. Filter the data for pig slaughters in Victoria between 1990 and 1995
pigs_vic_90_95 <- aus_livestock %>%
  filter(Animal == "Pigs",          # Select pigs
         State == "Victoria",       # Select Victoria
         year(Month) >= 1990,     # Select years from 1990 onwards
         year(Month) <= 1995)     # Select years up to 1995

# 3. Create a time series plot (autoplot) for the filtered data
pigs_vic_90_95 %>%
  autoplot(Count) +
  labs(title = "Monthly Pig Slaughters in Victoria (1990-1995)",
       y = "Number Slaughtered",
       x = "Month")

# 4. Create an ACF plot for the filtered data
pigs_vic_90_95 %>%
  ACF(Count) %>%
  autoplot() +
  labs(title = "ACF of Monthly Pig Slaughters in Victoria (1990-1995)")
```


```{r}
# Filter for the entire period for Victoria Pigs
pigs_vic_all <- aus_livestock %>%
  filter(Animal == "Pigs",
         State == "Victoria")

# Create ACF plot for the longer period
acf_plot_long <- pigs_vic_all %>%
  ACF(Count) %>%
  autoplot() +
  labs(title = "ACF of Monthly Pig Slaughters in Victoria (Full Period)")

# Display the plot
print(acf_plot_long)
```